#!/bin/bash

# fun color stuff
TRED=$(tput setaf 1)
TGRN=$(tput setaf 2)
TNRM=$(tput sgr0)

# The full file and path passed in to lint
fullFileName=$1;

# Clear the screen of any previous errors
clear;

PASS( )
{
   echo "${TGRN}"
   echo "                    __________  _____    _________ _________ "
   echo "                    \______   \/  _  \  /   _____//   _____/ "
   echo "                     |     ___/  /_\  \ \_____  \ \_____  \ "
   echo "                     |    |  /    |    \/        \/        \ "
   echo "                     |____|  \____|__  /_______  /_______  / "
   echo "                                     \/        \/        \/ "
   echo "${TNRM}"

}
FAIL( )
{
   echo "${TRED}"
   echo "                        ________________  .___.____ "
   echo "                        \_   _____/  _  \ |   |    | "
   echo "                         |    __)/  /_\  \|   |    | "
   echo "                         |     \/    |    \   |    |___ "
   echo "                         \___  /\____|__  /___|_______ \ "
   echo "                             \/         \/            \/ "
   echo "${TNRM}"
}

# Make sure the file to lint exists
if [ ! -f "${fullFileName}" ]; then
   echo "no such file $fullFileName to lint"
   exit 1;
fi

# Get the output of the lint command and its return code
result=$(npm run lint "${fullFileName}" 2>&1);
rc=$?

# Check the return code for pass/fail
if [ "${rc}" == "0" ]; then

   PASS

   # echo "No Errors found at this time";

else

   FAIL

   # Notifications are a pain as they hang around in the background
   # alerter -message "$result" -mute
   # Instead use osascript if we have it.
   if [ -x $( which osascript ) ]; then
      # orig osascript -e "tell app \"Terminal\" to display dialog \"${result//\"/}\""
      result="$(echo "$result" | sed -e 's/[\\"]//g')"
      osascript -e "tell app \"Terminal\" to display dialog \"${result//\"/}\""
   else
      // The characters around result stop malicious code
      // from being injected into our Terminal.
      echo "tell app \"Terminal\" to display dialog \"${result//\"/}\""
   fi
fi
exit 0;

